### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by kesslermaximilian** [cionx/writing-latex#4]
Could you provide a license?
I assume that - as you uploaded these to GitHub - you intend this to be free software, so I would appreciate it if you would provide a license.

I'd like to adapt some parts of your preamble etc.

**Comment by cionx** [comment]
I am definitely okay with people using and modifying the provided source code (or parts thereof) for their personal projects

I am not too familiar with open licenses, but I currently plan to go with CC-BY-4.0. From what I understand, this should allow everyone to use the contents of this project as well as its source code, while not restricting their personal choice of license. Feel free to inform me If I’m mistaken about this.

**Comment by kesslermaximilian** [comment]
yes, this would work, but for software, the CC licenses are usually not recommended, read e.g.

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

which e.g. recommends licenses from the following:

https://opensource.org/licenses

If you want to go for the most permissive (as is CC-BY-4.0 from the CC licenses), the MIT License should be fine (also because it is extremely short and easy to understand), for prohibiting commercial you can use the GPLv3.

Another option - especially regarding that this is LaTeX code - is to release this under the Latex Project Public License, which additionally obliges derived works to be named different than the original work, but probably this is not necessary as these aren't packages you intend do distribute on CTAN or something like that.

I personally use MIT, or (for package-like stuff) dual-license with LPPL and GPLv3, but I'm of course also not an expert and this might be personal flavor.

Thanks for the effort you are taking.

**Comment by cionx** [comment]
It seems to me that LaTeX projects and LaTeX code are somewhat curious when it comes to licenses. I’ve tried to find other projects that also should have this problem to see what they are doing:

- I think this project could be classified as somewhat of an open textbook. These seem to be mostly licensed under GPL (for example the [Stacks Project][1]), Creative Commons (for example the [HoTT book][2].) or something along the lines of “do what you want” like MIT, CC0 or Public Domain.

- The open access policies of publishers like [Springer][3], [Elsevier][4] or [CUP][5] seem to recommend their authors to use CC BY or stronger. But I don’t know if they have the publishing of LaTeX code in mind.

- Who should have the publishing of LaTeX code in mind is the arXiv: they seem to [mostly use Creative Commons][6].

- Tom Leinster’s book “Basic Category Theory” was [published in 2014 by CUP][CUP_basic], and then became freely available in 2016 [on arXiv][7]. The preface of this free version reads as follows:

  > This book was first published by Cambridge University Press in 2014, and is
now being published on the arXiv by mutual agreement. […] This electronic version is not only free; it is also freely editable. […] In legal terms, this text is released under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International licence (CC BY-NC-SA 4.0). […] Broadly speaking, the licence allows you to edit and redistribute this text in any way you like, as long as you include an accurate statement about authorship and copyright, do not use it for commercial purposes, and distribute it under this same licence. In technical terms, all you need to do in order to edit this book is to download the source files from the arXiv and use LaTeX […] in the usual way. […]

  It seems to me that at least in this case, the publisher (CUP) assumes that the choosen CC license also applies to the source code.

- The posts on [math.stackexchange.com][8], [tex.stackexchange.com][9], [stackoverflow.com][10], etc. are licensed under CC BY-SA 4.0.

I think the problem with LaTeX projects is that they often consists of roughly two parts:

- The actual content of the project, i.e., the actual text inside the document environment. This is, for most intense and purposes, basically plain text, enhanced with some markup elements to specify the structure of the document (`\section`, etc.), as well as some syntax for mathematical notations (`^` for exponents, `_` for indices, etc.).

- Some TeX code (or abstractions thereof) that is interpreted during runtime of the compiler.

After thinking about it for some time I came to the following conclusions (for now):

- I personally think that the GPL is too strong for this kind of project, as it forces everyone who wants to use parts of the project to also use the GPL.
 
- The MIT license seems to require attribution only in a rather weak sense: It is enough to simply retain a copy of the license file in the source code. For a LaTeX project, which will later be compiled into a PDF document, this basically removes the attribution. This is probably okay for projects that do not contain any actual content of their own (see next point), but I find it otherwise somewhat troublesome.

- The LPPL license is probably the correct approach for projects that do not contain any actual content on their own, e.g., packages or templates.

- A Creative Commons license can probably be used for projects that are about their actual content, and whose TeX components is (more or less) not so interesting.

In view of the above, I will probably put this project under CC BY-4.0. This should allow anyone to reuse its contents and its code, and the problems of using Creative Commons for code should hopefully not really matter for this specific project.

[1]: https://github.com/stacks/stacks-project
[2]: https://github.com/HoTT/book
[3]: https://www.springer.com/gp/authors-editors/authorandreviewertutorials/open-access/copyright-and-license/10286528
[4]: https://www.elsevier.com/about/policies/open-access-licenses
[5]: https://www.cambridge.org/core/services/open-access-policies/open-access-resources/creative-commons-licenses
[6]: https://arxiv.org/help/license
[7]: https://arxiv.org/abs/1612.09375
[8]: https://math.stackexchange.com/
[9]: https://tex.stackexchange.com/
[10]: https://stackoverflow.com/
[CUP_basic]: https://www.cambridge.org/core/books/basic-category-theory/A72533879BBC7BD956CC415777B7DA99

**Comment by kesslermaximilian** [comment]
Alright, seems like you looked into that deeper than I did myself, as I did not really think about differentiating internal tex code from typesetted documents (be it the source code, wich is mostly just text as you mentioned, or the processed document).
So I agree with your viewpoint here (I will also have to rethink licensing on my projects now...)

Thanks for spending your time with this (and for the great document, of course)!

**Comment by cionx** [comment]
I already added the LICENSE file to the [source repository][origin] last week (see commit 5c7730b16b77aa0435ccc3e74e05cfa12aa54f07), and have now also synced these changes to GitHub. (I originally wanted to fix the CI build before syncing the repositories, but it seems that this will take longer than expected.)

[origin]: https://gitlab.com/cionx/writing-latex
